language: php

php: [hhvm, hhvm-nightly]

before_install:
  - if [[ "$TRAVIS_PHP_VERSION" == hhvm* ]]; then echo 'hhvm.libxml.ext_entity_whitelist = "file"' > .travis.hhvm.ini; cat .travis.hhvm.ini fi

install:
  - COMPOSER_ROOT_VERSION=dev-master composer install --prefer-source

script:
  - if [[ "$TRAVIS_PHP_VERSION" == hhvm* ]]; then hhvm -c .travis.hhvm.ini bin/phpspec run; else bin/phpspec run; fi
  - if [[ "$TRAVIS_PHP_VERSION" == hhvm* ]]; then hhvm -c .travis.hhvm.ini ./vendor/bin/behat --format=pretty; else ./vendor/bin/behat --format=pretty run; fi
  - bin/phpspec run
  - ./vendor/bin/behat --format=pretty
